pipeline {
  agent any

  tools {
    jdk 'JDK17'
    maven 'Maven3'
  }

  stages {
    stage('Checkout Code') {
      steps {
        echo 'Pulling from Github'
        git branch: 'main',
            credentialsId: 'git',
            url: 'https://github.com/SanidhyaAulakh/wipjen.git'
      }
    }

    stage('Test Code') {
      steps {
        echo 'JUNIT Test case execution started'
        sh 'mvn clean test'
      }
      post {
        always {
          junit '**/target/surefire-reports/*.xml'
          echo 'Test Run is SUCCESSFUL!'
        }
      }
    }

    stage('Build Project') {
      steps {
        echo 'Building Java project'
        sh 'mvn clean package -DskipTests'
      }
    }

    stage('Build the Docker Image') {
      steps {
        echo 'Building Docker Image'
        sh 'docker build -t myjavaproj:1.0 .'
      }
    }

    stage('Run Docker Container') {
      steps {
        echo 'Running Java Application'
        sh '''
          docker rm -f myjavaproj-container || true
          docker run --name myjavaproj-container myjavaproj:1.0
        '''
      }
    }
  }

  post {
    success {
      echo 'Build and Run is SUCCESSFUL!'
    }
    failure {
      echo 'OOPS!!! Failure.'
    }
  }
}