pipeline {
  agent any

  tools {
    jdk 'JDK17'
    maven 'Maven'
  }

  stages {
    stage('Test Code') {
      steps {
        echo 'JUNIT Test case execution started'
        sh 'cd indiaproj && mvn clean test'
      }
      post {
        always {
          junit '**/target/surefire-reports/*.xml'
          echo 'Test stage completed.'
        }
      }
    }

    stage('Build Project') {
      steps {
        echo 'Building Java project'
        sh 'cd indiaproj && mvn clean package -DskipTests'
      }
    }

    stage('Build the Docker Image') {
      steps {
        echo 'Building Docker Image'
        sh 'cd indiaproj && docker build -t myjavaproj:1.0 .'
      }
    }

    stage('Run Docker Container') {
      steps {
        echo 'Running Java Application'
        sh '''
          cd indiaproj
          docker rm -f myjavaproj-container || true
          docker run --name myjavaproj-container myjavaproj:1.0
        '''
      }
    }
  }

  post {
    success {
      echo 'Build and Run is SUCCESSFUL!'
    }
    failure {
      echo 'OOPS!!! Failure.'
    }
  }
}